### PR TITLE
Release 1.2.0

### PR DESCRIPTION
**Pull request by Smankusors**
## Proposed changes
Releasing 1.2.0, also
1. seems like the original christinavoudouris goes missing, and I'm not sure the current one is actually the same person or different one?
2. the global.js needs manual version replacing... I will tackle this later

## Screenshots (if appropriate) or codepen:
N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md)**.
- [x] My commit messages follows the [conventional commit format](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md#submitting-your-pull-request)
- [x] My change requires a change to the documentation, and updated it accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by DanielRuf** [comment]
This (https://github.com/christinavoudouris) is still the same person. You can see on her LinkedIn profile.

I will check this in detail.

**Comment by mauromascarenhas** [comment]
Is it possible to await for #306 to be reviewed and merged? If so, we would have another component compatible with assistive technologies (sorry for not submitting it previously).

**Comment by mauromascarenhas** [comment]
> Is it possible to await for #306 to be reviewed and merged? If so, we would have another component compatible with assistive technologies (sorry for not submitting it previously).

#306 has been merged. I can't see any impeditive towards v1.2 release...

**Comment by wuda-io** [comment]
@Smankusors Do we need an additional manual commit for the changes of #306? So far it looks good to me.

**Comment by Smankusors** [comment]
> @Smankusors Do we need an additional manual commit for the changes of #306? So far it looks good to me.

@wuda-io oou wait, I will add it myself

**Review by wuda-io — APPROVED** [review]
Awesome!

**Comment by mauromascarenhas** [comment]
It seems that "dist" files were not updated after #306 had been approved... Are they going to be updated later as well?

**Comment by Smankusors** [comment]
> It seems that "dist" files were not updated after https://github.com/materializecss/materialize/pull/306 had been approved... Are they going to be updated later as well?

!!
goddamnit I forgot about this 🤦

**Pull request merged**
