### PR TITLE
[DRAFT] added prototype styling for dark theme support

### PR DESCRIPTION
**Pull request by bugy**
## Proposed changes
Here is a prototype of basic dark theme support. Theme variables are defined in sass/components/_theme_variables.css

By default `:root` variables are applied. If a `theme = dark` attribute added to `document`, then dark variables are picked up. In this way it would be possible to have even more than 2 themes per application if needed

I decided not to use css variables in scss files directly, but put them in scss variables (e.g. `$bg-color: var(--background-color) !default;`), this would be less breaking for users, who work with custom scss variables in their projects

I also adjusted tab/switch styling to better reflect material UI guidelines (and to use fewer variables).

If we would like to continue with this approach, I would kindly ask to merge #85 first, because there are quite some intersecting changes

Here is the testbed, which I used: https://materialize-testbed.s3-us-west-2.amazonaws.com/dark-theme/index.html#!
You can find theme switch in the right upper corner 

The switch theme code looks like this:
```
      if (darkTheme) {
        document.documentElement.setAttribute('theme', 'dark');
      } else {
        document.documentElement.removeAttribute('theme');
      }
```

## Screenshots (if appropriate) or codepen:
image
image

## Types of changes
It might be a breaking change for users, who override sass variables.
Also, it would change a look of some components (to better match material UI guidelines)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [x] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:
- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md)**.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by wuda-io** [comment]
Holy moly! This looks awesome!
Didnt look at the code yet, but the testbed you provided is really nice and looks good. I think we found the Sass Pro 😜👍

**Comment by nh916** [comment]
This is so beautiful!

I did not expect the first draft to be this beautiful!

**Comment by bugy** [comment]
Hi @nh916, thanks for the feedback :)

> Is each project able to overwrite the dark color to suite their own project and color schemes?

Yes, in each project you could define your own variable section and overwrite what you need, e.g.
```
:root[theme='dark'] {
--surface-color: red;
}
```
(or the same for a default theme)

In this way, you could also override only accent variables, e.g. use default styles but with orange color accent. (this is not available in prototype, though)

**Comment by Smankusors** [comment]
wait, is this still draft or no? If yes, then I shall convert this PR to draft pull request.

**Comment by bugy** [comment]
@Smankusors this is definitely a draft, please convert it (I couldn't find a way how to do it)

**Comment by Smankusors** [comment]
> @Smankusors this is definitely a draft, please convert it (I couldn't find a way how to do it)

hmm I found the button on the top right in this page. Maybe there's different role for that...

anyway, do you see the "Ready for review" button on this page? In case you are finished your PR, you can press this button so we can review and merge this. 😉

**Comment by bugy** [comment]
@Smankusors thanks! Yes, I see the "Ready for review" button

But I would kindly ask the members for review, as discussed in https://github.com/materializecss/materialize/issues/77#issuecomment-825466618

I.e. we should either agree on this approach, so I would proceed, or agree on another way, so I would drop it and start a different one from scratch

**Comment by DanielRuf** [comment]
> [DanielRuf](/DanielRuf) requested a review from [materializecss/members](/orgs/materializecss/teams/members) [gestern](#event-4647560337)

I think the others should be already aware =)

If not we can ping them again. But according to the reactions some of them are already aware of this PR.

**Comment by roiLeo** [comment]
I'm already in love with this feature!
I see that you are using css var but what would happen for ie user ? is there a polyfill ? are we droping ie support on v2 ?

Note:  I've found one small issue, the arrow of the select component in darkmode could need some color change
Screenshot_2021-04-28 Testbed

**Comment by bugy** [comment]
Hi @roiLeo thanks for the feedback! 
I'll prepare polyfill example also

**Comment by DanielRuf** [comment]
> I see that you are using css var but what would happen for ie user ? is there a polyfill ?

I think I have mentioned some available polyfills in https://github.com/materializecss/materialize/issues/77#issuecomment-824412340

**Comment by DanielRuf** [comment]
> Note: I've found one small issue, the arrow of select component in darkmode could need some color change

Nice catch, awesome!
I hope we can spot and fix more and then it's probably almost done =)

**Comment by bugy** [comment]
I tried with https://github.com/jhildenbiddle/css-vars-ponyfill and made css variables work with this code
```
import cssVars from 'css-vars-ponyfill'

cssVars({
  onlyLegacy: true
})
```
And _default_ styles worked properly in IE11.
But theme switching didn't work, since `:root[theme='dark']` syntax is not supported by this polyfill
To make theme switching work, we would need to use the special syntax from this library

To be honest, my suggestion would be:
1. Don't support theme switching on IE11 at all (only default theme)
2. Don't provide IE11 support out of the box
3. If anyone would need to enable IE11, they can add this polyfill to their project and activate it with a couple of lines of code 

Or we could also enable this polyfill in materializecss, but then we would increase the bundle size and almost no one would use it.

PS the updated code is available at the same link (with enabled polyfill and fixed dropdown caret color)
https://materialize-testbed.s3-us-west-2.amazonaws.com/dark-theme/index.html#

**Comment by DanielRuf** [comment]
Personally I would suggest to document the polyfill solution (in the documentation) and officially drop IE11 support. There are more than 1 polyfills per feature. That's why we used https://polyfill.io/v3/ in some projects.

**Comment by DanielRuf** [comment]
Personally I would suggest to document the polyfill solution (in the documentation) and officially drop IE11 support. There is more than 1 polyfill per feature. That's why we used https://polyfill.io/v3/ in some projects.

**Comment by nh916** [comment]
If Materialize Dark Mode is not supported on IE can we remove the Dark Mode toggle so it never even shows up if the user accesses the website from IE, but does show on supported browsers? I am thinking it would be bad user experience if the user goes to a to hit the toggle for Dark Mode and is greeted with no change or feedback, left to wonder if something is wrong with their computer, the website, or just this button.

However, I do agree that dropping support for IE is probably a good idea because otherwise it would make our framework too big and in most cases it is not needed. However, if there is a project that does need it we can have clear documentation to allow users to easily add in the support for IE if they need it.

**Comment by bugy** [comment]
@nh916 sure, it goes without saying :) I'll do it if we agree on going the way with css variables and not supporting theme switching in IE

**Comment by nh916** [comment]
What happened to this PR? How come its just sitting in limbo, this is a really awesome feature that I would love to have in my future projects!

**Comment by DanielRuf** [comment]
> What happened to this PR? How come its just sitting in limbo, this is a really awesome feature that I would love to have in my future projects!

It is still a draft PR and it is planned for v2 ;-)

**Comment by bugy** [comment]
Hi @nh916 this was just a prototype, to foster discussions.
To proceed with full implementation we need to:
- agree on css variables approach
- agree on what to do with IE
- create v2 branch
- merge #85 

The last do not bring much at the moment, since the team is focused on 1.1 stable release
For the first 2, @DanielRuf should i organize some poll, and we ask all the members to vote?

**Comment by L1ghtn1ng** [comment]
As microsoft are getting rid of IE we do not need to worry about it

**Review by wuda-io — APPROVED** [review]
LGTM. It looks like there would be a complete Theme-Configuration (no only DarkMode) possible.
I also need this. When do we merge? We should start with v2 ASAP!

**Comment by godalming123** [comment]
```js
function setCookie(cName, cValue, expDays) {
        let date = new Date();
        date.setTime(date.getTime() + (expDays * 24 * 60 * 60 * 1000));
        const expires = "expires=" + date.toUTCString();
        document.cookie = cName + "=" + cValue + "; " + expires + "; path=/";
}

function getCookie(cName) {
      const name = cName + "=";
      const cDecoded = decodeURIComponent(document.cookie); //to be careful
      const cArr = cDecoded .split('; ');
      let res;
      cArr.forEach(val => {
          if (val.indexOf(name) === 0) res = val.substring(name.length);
      })
      return res;
}

function setTheme(isDark) {
    if (isDark) {
        document.documentElement.setAttribute('theme', 'dark');
    }
    else {
        document.documentElement.removeAttribute('theme');
    }
    setCookie("darkTheme", isDark.toString(), 10);
}

function getIsDark() {//get true if the system theme is dark false otherwise
    const darkThemeMq = window.matchMedia("(prefers-color-scheme: dark)");
    darkThemeMq.addListener(e => {
        if (e.matches) {// Theme set to dark.
            return true
        }
       else {// Theme set to light.
           return false
       }
    });
}

initTheme () {
    if (getCookie("isDark") == "") {//if the cookie is not set
        setTheme(getIsDark())
    }
    else {//if we have set the cookie
        setTheme((getCookie("isDark") === "true"))//set the page theme and reload the cookie so it won't expire
    }
}

```
After thinking about the duplication of the code above to change the theme depending on system theme I think this code is better it's still a non breaking change as you have to call `initTheme()`

**Comment by godalming123** [comment]
loving this dark theme could you deploy on github pages release this would allow us to test every single component in the docks by setting the `theme` attribute with devtools? Just do this:
 
1. go to the settings tab on the repo.
 
2. select pages from the sidebar on the left

3. change the value in the dropdown from none to whatever branch you made the changes on
 
4. click save and after about 2 minutes github will build your site when your site is built it will say your site is published at _somewhere_ but it will actually take another 6 or so minutes to deploy than you can visit the link and see your changes. if you get an error when doploying it is likely because your scss is invalid and you can then fix it.

image

**Comment by bugy** [comment]
Hi everyone, sorry for being silent here
This PR is only a draft to show the implementation proposal
I'll try to find some time this/next week to make it up to date with the latest changes and making it more generic
After that, there will be some work to apply the dark style for every component

To be honest, i wouldn't include cookies/default theme in this PR. We should start just with the possibility to configure a theme. And then the library users would decide how the configuration will be stored (e.g. some user settings on backend)

**Comment by AurelienTisserand** [comment]
> Hi everyone, sorry for being silent here This PR is only a draft to show the implementation proposal I'll try to find some time this/next week to make it up to date with the latest changes and making it more generic After that, there will be some work to apply the dark style for every component
> 
> To be honest, i wouldn't include cookies/default theme in this PR. We should start just with the possibility to configure a theme. And then the library users would decide how the configuration will be stored (e.g. some user settings on backend)

100% agree I wouldn't include cookies into this PR. In my own web applications we don't want to use cookies at all so we do not want to be forced to use one for that purpose

**Comment by bugy** [comment]
I resumed working on this PR. Unfortunately to make rebase easier, I've moved everything to a new PR: #254

**Comment by nh916** [comment]
bump

do we have any progress on this?

**Comment by bugy** [comment]
Hi @nh916, good question. When I created a new PR, #254 i didn't get any feedback
Also, as far as i remember, there were talks, that the project week be suspended, due to argues.
As i see now, the project is alive again, and i can continue on PR, if I get GO. Otherwise i do not want to work on PR which will never be merged

@DanielRuf should I proceed?

**Comment by DanielRuf** [comment]
@bugy feel free to proceed with the PR. There is no pressure and there are no obligations.

So it's also fine if things are not finished. As this is an open source project and no one gets paid for their work, no one can expect that things get prioritized.

**Comment by DanielRuf** [comment]
Regarding https://github.com/materializecss/materialize/pull/254, no group was assugned as revuewer so no one was informed via notifications.

Which PR is the latest status and which PR can be closed @bugy?

**Comment by bugy** [comment]
@DanielRuf, cool, thanks for the response. To be honest, I don't remember, why I didn't assign any reviewers. 
#254 is the latest. This one can be closed

**Comment by DanielRuf** [comment]
> This one can be closed

Thanks for the clarification. Done.

**Pull request closed without merging**
