### PR TITLE
fix(doc): invalid download sass link

### LINKED ISSUE #127: Invalid link for Sass version
The `SASS` button on the documentation point to the following URL: `https://github.com/materializecss/materialize/releases/download/1.1.0-alpha/materialize-src-v1.1.0-alpha.zip`.

## Expected Behavior

I was expecting to download a zip with the following structure:
```
  |--js/
  |  |--bin/
  |
  |--scss/
  |  |--materialize.scss
  |  |--components/
  ```

## Current Behavior

This file does not exist, or is now missing.
I could download the entire repository, clean it, but I don't know how to build the `materialize.js` and `materialize.min.js`.

## Possible Solution
Maybe something is missing from the current release flow.
I would be nice to have this version available, as it was supported before and help people getting started quickly with materializecss.

## Steps to Reproduce (for bugs)

Click the SASS `SOURCE` button.

## Context
I am new to web development (I come from the back-end side) and I was trying to get the sass version of materialize theme.

## Your Environment
* Version used: https://materializecss.github.io/materialize/getting-started.html
* Browser Name and version: Chrome (90.0.4430.93 - Official Build - 64-bit)
* Operating System and version (desktop or mobile): Windows 10 (Build 21370.1)

### PR DESCRIPTION
**Pull request by roiLeo**
close #127

### CODE REVIEW

**Review by wuda-io — APPROVED** [review]
LGTM

**Review by DanielRuf — APPROVED** [review]

**Comment by DanielRuf** [comment]
> wait, what? Nooo............ what's the purpose of 2 buttons leading to the same link? disappointed

Good catch.

Can you revert the commit and provide a new PR @roiLeo?

**Comment by Smankusors** [comment]
IMO, I would just commit the updated link without PR, we don't need to revert it.

**Comment by DanielRuf** [comment]
> IMO, I would just commit the updated link without PR, we don't need to revert it.

See my last comment. I already reverted it.
A PR should be the way to go so it goes through the review process.
I think we should make the current v1-dev branch protected to allow only changes by PRs.

We are not in a hurry so we can wait for a PR.

**Comment by roiLeo** [comment]
Original [repo](https://github.com/Dogfalo/materialize/releases) had 2 two .zip in last release, one with compiled css/js (materialize.css and materialize.js) and the other one with uncompiled sass/js files.
Maybe we should remove the sass download links, as we do not currently provide an archive containing sass files.

**Comment by ChildishGiant** [comment]
well github still generates a source code zip that we could use? If we want to make a proper src zip like they have with all the extras not included, we should build it into the release script.

**Comment by wuda-io** [comment]
Yes, the best solution is to generate the link out of the Process, otherwise we will face the same issue again at the nexr Release.

**Comment by Smankusors** [comment]
> Yes, the best solution is to generate the link out of the Process, otherwise we will face the same issue again at the nexr Release.

the release process is just search "old version string" and replace it with "new version string". So as long as the link have similarity, I think it should be fine.

**Comment by ChildishGiant** [comment]
I more mean make the script generate these zips, not just making them by hand each time.

**Comment by Smankusors** [comment]
hmm... or maybe just point the link to the github repo? Instead of src zip file?

**Pull request merged**
