### PR TITLE
Update husky version

### PR DESCRIPTION
**Pull request by wuda-io**
## Proposed changes
The Commit-Message was not checked properly for many contributers, due to an old or outdated version of Husky and Commitlint. I updated the package.json File and added a required Commitlint-File. It works now on my machine, i re-installed node_modules with the new packege.json File and it works now. I hope this prevents future issues with it.

## Screenshots (if appropriate) or codepen:
grafik

## Types of changes
Updated the version of Husky and Commitlint. Also tested on a windows machine.

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:
- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by wuda-io** [comment]
What is **package-lock.json** for? Is it also needed to add in some Commits / PRs or should we add it to gitignore?

**Comment by DanielRuf** [comment]
package-lock.json is the lockfile generated by npm. Please always commit changes in there so all contributors have the same dependency versions.

**Comment by wuda-io** [comment]
OK, I added the package-lock file and also ran `npm update` on it. Is this ok?

**Review by LoganTann — APPROVED** [review]
Looks good !

I will merge it and try that.

**Comment by LoganTann** [comment]
image

works well, thanks for the contribution !

**Comment by rdevroede** [comment]
The postinstall should only run husky when it exists, as it is a devDependency. Upgrading on a regular environment is now broken:

npm ERR! command failed
npm ERR! command sh -c husky install
npm ERR! sh: 1: husky: not found

**Comment by DanielRuf** [comment]
Hi @rdevroede,

we just have to make a new release. See https://github.com/materializecss/materialize/commits/main/package.json.

Can someone handle this @materializecss/maintainers?

**Comment by wuda-io** [comment]
> Can someone handle this @materializecss/maintainers?

I will try to do a new release 1.2.1

**Pull request merged**
