### PR TITLE
Modal with Html5 dialog element

### LINKED ISSUE #528: [Bug]: Modal footer padding not consistent to modal content area
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

The Materialize modal footer is not respecting the Material guidelines

### Current Behavior

When implementing the Materialize modal, the footer is not respecting the Material guidelines, padding-bottom is hard-coded at 4px while guidelines suggest a padding of 24px
Comparing the Modal component footer section against the Modal component content sections, inner paddings are not appropriate aligned against eachother

**Screenshots**
Screenshot 2024-11-08 at 13 53 56
_Footer padding is not aligned with content padding, right bottom button corner is cut off_

### Expected behavior

Modal should respect the inner paddings as described by the Material guidelines
Buttons should be fully visible when placed in the footer

### Possible Solutions or Causes

Apply modal-padding variable in Modal component footer element styling and remove fixed height

### Steps to reproduce

1. Implement the Modal component
2. Try out these scenarios
    2.1. Inspect the paddings with browser inspector: paddings not consistent
    2.2. Try out a different button styling as proposed: button corner is cut off

### Your Environment

* Version used: 2.1.1
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Additional information you want to tell us:

### PR DESCRIPTION
**Pull request by wuda-io**
## Proposed changes
Change existing Modal Component so that it can be used with stadard [Html5 dialog](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) element.
See issue #525
Also fixes #528

## Screenshots (if appropriate) or codepen:
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [x] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md)**.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by gselderslaghs** [comment]
Its difficult to review, what HTML changes would be needed compared to the previous setup? Can you provide a code snippet that would work with this setup?

I notice in the documentation change inline javascript function handlers where implemented and the previous method of id referencing is abandoned, not really like this idea since it would introduce reduction to the semantics of the web pages more specific for screen readers and crawling bots since the reference between link and modal is currently only javascript based, I think we should keep the href=#anchor and id=anchor references by changing back from onclick to href from the point of view on web semantics

The approach with click handlers specifically targetting the modal instance using inline javascript method call handlers would also be more complex to setup in particular frameworks since there would be additional onclick handlers on the html element as of before we could just use the id referencing and the modals opening and closing works out of the box

**Comment by gselderslaghs** [comment]
Can you describe a scenario with where initialization fails because of refreshing the elements? Guess it's we should create an issue and fix them then..

I'm currently working on a project fork for [Drupal Materialize - Google Material base](https://www.drupal.org/project/materialize/) where I'm [replacing the old Materialize version with the new one](https://www.drupal.org/project/materialize/issues/3486581), this is particular in the Drupal framework and would require elements initialization with JavaScript options rather then changing the HTML elements, since requiring attributes in the HTML element would require additional templating vs processing the options from PHP to JavaScript components options directly would not require any additional template updates, this is also the reason why I created #559

**Comment by wuda-io** [comment]
> Can you describe a scenario with where initialization fails because of refreshing the elements? Guess it's we should create an issue and fix them then..

The problem with the init methods are, that they are often forgotten to be called and then people ask why does it not work etc. Also when the html-elements of the page are changed, they have to be re-initialized, which is also a soruce of many errors. So the best init method is no init method at all.

I think we can use the popover feature here.
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover

Upgrade example would then be from
```<button data-target="modal1" class="btn modal-trigger">Modal</button>```
to
```
<button popovertarget="my-popover">Open Popover</button>
<div popover id="my-popover">Greetings, one and all!</div>
```
1. replace `data-target` with `popovertarget`
2. add `popover` attribute to all elements with class `modal`

Then we can also keep the tagnames (no dialog needed). Also it works without JS at all.

**Comment by wuda-io** [comment]
Ok I will merge it for now to make the release. I know it is not perfect, but we can keep up with fixes until it fits for broad mass. I think we should make a transition to the new Popover API. It is really cool and easy to use!
I think we should aim for 2.2.0 due to many changes.

**Pull request merged**
