### PR TITLE
Component and option type definitions + code docs

### PR DESCRIPTION
**Pull request by mauromascarenhas**
## Proposed changes

Apply type definition for every Materialize component (I have taken some from DefinitelyTyped, since I'm the maintainer of `@materializecss/materialize` types).

- Base Component is a generic class with "BaseOptions" interface:
    - Declared function overloades for component initializer;
    - Declared "virtual" methods and given a proper documentation for them.
- Every component (except by `Toast`) inherit from `Component` and their respective options from `BaseOptions`;
- Removed "circular" dependencies (check "Breaking changes");
- Added missing types to event handlers and their respective args;
- Component `options` is no longer "protected" (the user should be able to check the initialization options as well, just as mentioned in the docs);
- Fixed:
    - Undefined instance reference in Collapsible "destructor";
    - Touch event handler when target does not have a close carousel item;
    - Type definitions using "Boolean" object as type.

### Breaking changes

- Completely removed native support to jQuery;
- Unused methods, such as `M::objectSelectorString`, have been removed;
- Global utility functions and variables have been migrated to "Utils" module, which is available under "`M.Utils`" (this is an important change, since it removes circular dependency from the component sources 😃).

### Affected PRs:

- #351 Should be closed, since it would become redundant;
- #370 Should be refactored in order to match component types;
- #387 Should be refactored in order to be merged;
- #388 Should be closed, since it would become redundant.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [x] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md)**.
- [x] My commit messages follows the [conventional commit format](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md#submitting-your-pull-request)
- [ ] My change requires a change to the documentation, and updated it accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by danice** [comment]
Great work!
One thing: I have tested the changes in [this test project](https://github.com/danice/materialize-docs-webpack) an it gives errors for the init method:

imagen

The reason is that querySelectorAll returns a ``NodeListOf<Element>`` instead of ``NodeListOf<HTMLElement>``.
One possible solution to avoid having to add this ``querySelectorAll<HTMLElement>`` all the time would be changing the init parameters to 

```
static init(els: InitElements<Element>, options: Partial<CarouselOptions>): Carousel[];
```
instead of the 
```
static init(els: InitElements<HTMLElement>, options: Partial<CarouselOptions>): Carousel[];
```

What do you think?

**Comment by mauromascarenhas** [comment]
> Great work! One thing: I have tested the changes in [this test project](https://github.com/danice/materialize-docs-webpack) an it gives errors for the init method:
> 
> imagen
> 
> The reason is that querySelectorAll returns a `NodeListOf<Element>` instead of `NodeListOf<HTMLElement>`. One possible solution to avoid having to add this `querySelectorAll<HTMLElement>` all the time would be changing the init parameters to
> 
> ```
> static init(els: InitElements<Element>, options: Partial<CarouselOptions>): Carousel[];
> ```
> 
> instead of the
> 
> ```
> static init(els: InitElements<HTMLElement>, options: Partial<CarouselOptions>): Carousel[];
> ```
> 
> What do you think?

Well, I haven't noticed it. Thanks for reporting.
I'll replace this type requirement in initialization functions and constructors.

**Comment by mauromascarenhas** [comment]
@danice, I've made some changes to the initialization overloads which allows "Element" type to be considered as well 😄. The following snippets illustrates a picker being initialized either by a single element (even though it is typed as `HTMLInputElement`) or by a `NodeListOf<Elements>`.

Initialization samples of TimePicker

I've also updated component initializers so as to allow "empty" options 😃.

**Comment by wuda-io** [comment]
Haha good work! That will take some time to review :laughing: I will check locally...

**Comment by mauromascarenhas** [comment]
I've just had to merge v2-dev into this branch, since #387 has been already merged, thus, requiring a small refactor, as mentioned [in the topic](https://github.com/materializecss/materialize/pull/390#issue-1766764514).

**Comment by wuda-io** [comment]
Awesome! Great work :+1: 
I see you used some sort of documentation tool in your code. Is this TSDoc?

**Comment by mauromascarenhas** [comment]
It is JSDoc as well.
Since TS is a superset of JS, most of JSDoc tags also work with TS.

**Pull request merged**
