### PR TITLE
fix(dropdown): 🐛 fix a bug with dropdown actives when used in selects

### LINKED ISSUE #133: Options in select element still highlighted after unselecting it.
Peek 2021-05-05 20-58

### PR DESCRIPTION
**Pull request by ChildishGiant**
This would close #133

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by bugy** [comment]
I'll check the changes and test them in the evening.

**Comment by bugy** [comment]
As a solution, I found this one: https://stackoverflow.com/a/48500276/2166673

It might be not supported in some browsers, but as for me, those browsers can live with a default non-smooth scroll

**Comment by DanielRuf** [comment]
Any update regarding the last comment?

**Comment by DanielRuf** [comment]
Hey,

You might be busy but I just wanted to check if there is an update regarding the last comment.

**Comment by ChildishGiant** [comment]
https://user-images.githubusercontent.com/13716824/120933359-bc176580-c6f1-11eb-89a1-bcb71b42ebf3.mp4

I've checked again and I'm still not having issues. Could you show the issues you're having?

**Comment by bugy** [comment]
Hi @ChildishGiant, sorry if I'm doing something wrong, but I still have the problem

https://user-images.githubusercontent.com/1275813/120935730-6bf5ce80-c704-11eb-8f66-d6cb22d46776.mp4

I'm testing in Chrome, and using my own testbed + vue. I don't use compiled dist.js file, but rather dropdown.js directly. May be you could try rebuilding the dist file locally? 
Otherwise, I don't know what could be the issue :(

**Comment by ChildishGiant** [comment]
I've cloned the repo to a different folder, switched branch and built with no issues showing. Are you sure you're on the right branch and have built after changing over? If anyone else could check this that'd be great

**Comment by bugy** [comment]
Alright, I found where our testing issue is: autocomplete uses custom handling for up/down keys. see autocomplete.js `_handleInputKeydown`
Could you try testing with a normal dropdownm please?

**Comment by ChildishGiant** [comment]
Ah, there we go. Thanks for pointing that out. Should be all fixed on all kinds of dropdowns now.

**Comment by bugy** [comment]
Thanks for the fix! But could we go with the `focus()` approach? It would also solve this problem (from #133):
> Another problem which I see now, is that the list elements are not focused anymore. document.activeElement always returns <ul> element, instead of <li>

**Comment by ChildishGiant** [comment]
I've updated it to the method you've linked and agree that it is better. I'm sorry for the continued back and forth about this issue. Using smooth scroll combined with the background transition does cause readability while holding to scroll to not be great, sadly. The only real option to fix this would be lower the transition time and disable smooth scroll but I think maybe it's best to keep it as is.

https://user-images.githubusercontent.com/13716824/121007803-24198a80-c78a-11eb-88f4-7949b9b365db.mp4

**Comment by bugy** [comment]
Looks good, thanks!

**Review by bugy — APPROVED** [review]

**Comment by wuda-io** [comment]
I also have the issue when clicking on Dropdowns of the Select Elemrnt in the current Website. Whats the status of this fix? Looking forward for a merge. Greets

**Pull request merged**
