### PR TITLE
Add functions to initialize textarea and the File Input Path created programmatically

### PR DESCRIPTION
**Pull request by OlivierMadant**
## Proposed changes
The current Forms.Init() function creates a DOMContentLoaded event which, when fired, will initialize the textareas and File Input Path present when the dom is loaded.
This mean that if we create a texarea programmatically, calling the Forms.Init() function will do nothing on the new created textarea.
We currently have no way to call the js code needed to initiate the textarea using the available functions.

That Pull request add the functions that will allow us to initialize the textarea and the File Input Path created programmatically.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md)**.
- [x] My commit messages follows the [conventional commit format](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md#submitting-your-pull-request)
- [ ] My change requires a change to the documentation, and updated it accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by OlivierMadant** [comment]
If the proposal is validated, I will adapt the documentation accordingly :-)

**Comment by wuda-io** [comment]
Can you please change the commit messages into the correct format. Thank you.
Otherwise looks good :+1:

**Comment by OlivierMadant** [comment]
Hello,

Thanks for the feedback.
I updated the commit messages. 
I will prepare another PR for the documentation.
Have a nice day!

**Comment by OlivierMadant** [comment]
The documentation has been adapted accordingly.
Thanks in advance for the review!

**Review by wuda-io — APPROVED** [review]
LGTM

**Pull request merged**
