### PR TITLE
docs: Fix grammar

### PR DESCRIPTION
**Pull request by astonizer**
## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md)**.
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Smankusors** [comment]
eh huh? I wondering why "patreon june" commit sometimes shown in PR 😕

**Comment by DanielRuf** [comment]
> eh huh? I wondering why "patreon june" commit sometimes shown in PR 😕

Probably because it was a fork frm the original repo.

@astonizer please drop the patreon commit with `git rebase -i HEAD~2` using `drop`.

**Comment by astonizer** [comment]
Tried `git rebase -i HEAD-2` but throws an error saying `fatal: invalid upstream 'HEAD-2'`
I've not worked much with rebasing so it's difficult for me to figure it out. 
Thinking of a fresh fork and redoing the changes.

**Comment by astonizer** [comment]
I guess I messed up my fork. I'll re-fork and try again.

**Comment by Smankusors** [comment]
> Tried `git rebase -i HEAD-2` but throws an error saying `fatal: invalid upstream 'HEAD-2'`
> I've not worked much with rebasing so it's difficult for me to figure it out.
> Thinking of a fresh fork and redoing the changes.

oh no, you mistyped it, it's `HEAD~2`, not `HEAD-2` 😅

**Comment by DanielRuf** [comment]
You need tilde (~), not HEAD-2.

**Comment by DanielRuf** [comment]
Also please create a separate branch to prevent conflicts with new changes on our dev branch @astonizer.

**Pull request closed without merging**
