### PR TITLE
Revert "Refactored sidenav css to accommodate btns better"

### PR DESCRIPTION
**Pull request by nekonenene**
## Proposed changes

This PR reverts commit bafde665e7b600fc273d0b00596aa52860109206 because it breaks sidenav style.

It is better to understand the motivation for his change, but I don't have any way because this commit doesn't associated to any issues or pull requests, so I decided to simply revert.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by Smankusors — COMMENTED** [review]
ou yeah I just noticed this.... thanks for investigating which commit caused it tho 😅 

---

btw... on the other story, Forms > Chips also have weird underline on the input field, while on the materializecss.com not... 😟

**Comment by nekonenene** [comment]
> on the other story, Forms > Chips also have weird underline on the input field, while on the materializecss.com not... 😟

Ugh... it seems to come from this change.
https://github.com/Dogfalo/materialize/pull/6313/files

I'm appreciate if you create this issue.

**Comment by nekonenene** [comment]
@Smankusors I created the PR now! 🎉 https://github.com/materializecss/materialize/pull/34

**Comment by mau5ken** [comment]
This looks great! Very appreciated <3

**Review by DanielRuf — APPROVED** [review]

**Comment by DanielRuf** [comment]
> This looks great! Very appreciated <3

Thanks for the feedback. Keep in mind that you can also do a review as member of the members group.

**Pull request merged**
