### PR TITLE
docs: change to/add copy code icons

### PR DESCRIPTION
**Pull request by christinavoudouris**
I've added the first run of 2 copy code icons to the Getting Started page. The Clipboard API doesn't seem to work locally but I imagine will work when we push the changes live. Here is a codepen of the changes for reference as well:

https://codepen.io/christinavoudouris/pen/oNWqYLK

If these look good, I can go ahead and add them throughout the site.

### CODE REVIEW

**Comment by warrenrodrigues** [comment]
I see a couple of issues with this:
1. The event listener is initialized after the first click, so the copy starts working only from the second click onwards.
2. The ClipboardAPI requires additional user permission when `readText` is used. Your code seems to work without this line
`navigator.clipboard.readText(copiedText[i].innerText);`
Do we need this for something that perhaps I'm missing?

clipboard-permission

**Comment by christinavoudouris** [comment]
Thanks @warrenrodrigues! You're right about the readText(), it doesn't seem to be necessary. I've also wrapped everything in another event listener. See the updated Codepen.

**Comment by warrenrodrigues** [comment]
Thanks. Had a look and forked it with further updates here - https://codepen.io/warrenrodrigues/pen/ZEKoLWP
Since you're using an event listener, we don't need the `onclick="copyText()"` on each element. And we can also change the `copyText` function in JS to an anonymous function.

**Comment by christinavoudouris** [comment]
Good call! I've updated the code in the repo and moved the styles into the larger sass file as well.

**Comment by warrenrodrigues** [comment]
Thank you for all your work @christinavoudouris

I have found a couple of other things that need fixing.
- The copy button throws a `Cannot read property 'innerText' of undefined` error. This is because the `<code>` tag has an id, while the JS is querying by class.
- You have `id="copiedText"` multiple times in each file. As per specs, an ID can only be used once per page. So instead of
`<code class="language-javascript" id="copiedText">`
we can do
`<code class="language-javascript copiedText">`

This change fixes the undefined error too.

That said, I would like someone else's opinion on whether we can use HTML code between the `<pre>` and `<code>` tags. I would rather enclose the whole thing in a `<div>` tag, like this
```
<div>
  <span class="copyMessage">Copied!</span>
  <i class="material-icons copyButton">content_copy</i>
  <pre><code class="language-javascript copiedText">
var instance = M.Carousel.getInstance(elem);
  </code></pre>
</div>
```

**Comment by christinavoudouris** [comment]
Oh, I must've grabbed the older code by mistake, in regards to the ID. This was changed to class a while ago. I did notice that error but I assumed it was because I was viewing the docs locally.

I'm open to changing the code a bit to using <div>. I'll make

**Comment by christinavoudouris** [comment]
@warrenrodrigues What would be gained by adding a div tag around the button? From what I'm seeing it creates a bit more code. Would it fix a cross-browser issue or do you think it just makes the code more readable? As a React dev, I try to use Fragment as much as possible so I don't create more divs for no reason.

I've rebased my commits with the class now in place so this PR should be easier to review thus far. I'm going to hold off on adding more buttons until we resolve this so I don't have to do a massive find/replace again.

**Comment by warrenrodrigues** [comment]
Thank you for the updates @christinavoudouris 

Generally, I would also avoid adding extra `<div>`s. However, from what I understand, the `<pre>` element represents a block of preformatted text. It maintains spaces and new lines, unlike how all other HTML tags behave. So I think it's best to leave the `<pre>` container for the actual _code_ only. Would love to hear your opinions on this @DanielRuf @ChildishGiant 

Yes, best to hold off on further updates, till this is finalized.

**Comment by christinavoudouris** [comment]
@warrenrodrigues Yeah, I ended up adding an additional inline style for the pre containers I put the button in so there's no extra padding. Wasn't sure how to go about this within the stylesheet considering the :before and :after. Any tips there are appreciated. 

I also opted to leave buttons off for very short examples like instance.open(), etc.

**Comment by DanielRuf** [comment]
Hi @warrenrodrigues @christinavoudouris,

what is the current status of this PR?

Is this still wip / draft or can it be reviewed?

**Comment by christinavoudouris** [comment]
Hey @DanielRuf  and @warrenrodrigues just checking in ... what's the consensus on using pre vs. divs? Has anyone else given an opinion? I am open to either. If we can come to a decision I can put in the rest of the icons and we can finally merge this thing.

**Comment by DanielRuf** [comment]
Hi @christinavoudouris,

so far I have used `<pre><code...` when something should be displayed / marked as preformatted code so I think this is better than `<div>`.

**Comment by warrenrodrigues** [comment]
Hi @DanielRuf 

Please see [this comment](https://github.com/materializecss/materialize/pull/161#issuecomment-892535621)
It's about including the copy button and "Copied!" message within the `<pre>` tag, which I think should be avoided. I think `<pre><code...` should be reserved only for the actual code block; not for the copy button and message.

Does this make sense?

**Comment by DanielRuf** [comment]
> Does this make sense?

> That said, I would like someone else's opinion on whether we can use HTML code between the <pre> and <code> tags. I would rather enclose the whole thing in a <div> tag, like this

Thanks, yes we should wrap them in a div.

**Comment by christinavoudouris** [comment]
@warrenrodrigues @DanielRuf Thanks guys. I feel like I've contributed a lot here and if there are going to be this many changes, feel free to reopen a new PR and take over. Might be worth just pushing what we have since at least some of the buttons work, and then do the rest.

**Comment by DanielRuf** [comment]
> @warrenrodrigues @DanielRuf Thanks guys. I feel like I've contributed a lot here and if there are going to be this many changes, feel free to reopen a new PR and take over. Might be worth just pushing what we have since at least some of the buttons work, and then do the rest.

You definitely rocked this, thank you very much for the great work. I think we can make a small cut here and merge this as is.

Does someone want to make a follow up PR? That would be awesome.

**Comment by DanielRuf** [comment]
Does someone want to make a follow up PR? That would be awesome. @materializecss/members

**Pull request merged**
