### PR TITLE
Timepicker accessibility #476

### PR DESCRIPTION
**Pull request by gselderslaghs**
## Proposed changes

Fixes & enhancements based on https://github.com/materializecss/materialize/issues/476

- [X] Layout mismatch on mobile spec
- [X] Layout light theme: color mismatch on input fields in timepicker component
- [X] Event listeners: Refactored click listeners to focus listener, this is more specific and detects focus by keyboard tabbing
- [X] Input hours field: fix leading zero's consistency
- [X] Input hours/minutes: introduced focusout event listener, moved leading zero's to focusout event listener since they are interrupting keyboard input and reduce accessibility
- [X] Extend twelveHour option in inputFromTextField method
- [X] Remove autofocus on change since it's interrupting keyboard input and reduce accessibility
- [X] Make submit/cancel buttons more accessible, introduce focussability and tabbability
- [X] Fix bug in 24hour user input where hand was not placed correctly on analog clock when changing clock value manually in digital display

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue).
- [X] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:
- [X] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md)**.
- [X] My commit messages follows the [conventional commit format](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md#submitting-your-pull-request)
- [] My change requires a change to the documentation, and updated it accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by Jerit3787** [comment]
Hi @gselderslaghs, please rebase all PR to branch v2-dev. Thanks

**Comment by gselderslaghs** [comment]
Reviewing my work. Not sure if this PR is fully correct, since I've implemented button classes (L411) and as there are multiple options available, hard-coding the button style would reduce the availability of different button styles when implementing this component.

Since the framework has different button styling available I might need to refactor the codebase in order to apply the button styling variations as an option in the component initializaton. Anyway, not defining a button style might result in accessibility reduction. This also applies to other components in the component library.

- Should we apply the definition of button styling as a global function instead (eg. based on selected theme)?
- Should we apply a solution for scenarios where default styling/theme is defined and no button classes are added, so as a result the buttons get focussed anyway?

**Review by wuda-io — APPROVED** [review]
LGTM. I think in the near future we should aim to use [Temporal](https://tc39.es/proposal-temporal/docs/) for better date time handling.

**Comment by wuda-io** [comment]
I like the ideas with the Button styling. We should discuss this in a new issue.
I sent you an invitation to join the team. Thank you for the clear PRs.

**Comment by gselderslaghs** [comment]
> LGTM. I think in the near future we should aim to use [Temporal](https://tc39.es/proposal-temporal/docs/) for better date time handling.

@wuda-io
I just reviewed the merge commit and noticed there is still an invalidity in CSS styling declaration
This particularly happens within media query match between 601px and 734px (see attached screenshots)
I propose we should use fixed widths for the input fields instead of depending on width percentage within this media query match
Screenshot 2024-11-14 at 14 32 21
Screenshot 2024-11-14 at 14 36 40

I would suggest reopening #476 as I will review and fix the mentioned issue in the next commits

**Pull request merged**
