### PR TITLE
Add maintainers doc

### PR DESCRIPTION
**Pull request by Smankusors**
## Proposed changes
In this PR, I would like to propose a documentation for the maintainers. So that if I'm not available and/or someone else would like to move this forward in the future, at least we will know what should be done.

In this document, I added 3 sections, which is labels, releasing a new version, and generating a changelog.

Let me know what do you think about this.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by LoganTann — COMMENTED** [review]
Need a second review from someone who haves a push access to this repo

**Comment by Smankusors** [comment]
btw I just realized the existence of `M.version`... I think for someone who will release the next version, please make sure to update this variable 😅 

might need to fix the grunt release script too 🤔

**Review by wuda-io — APPROVED** [review]
Thanks for documenting the process

**Comment by jshster** [comment]
Thanks so much for doing this.  Will be reading through ASAP.

**Comment by wuda-io** [comment]
What is missing to do the merge?

**Pull request merged**
