### PR TITLE
updated normalize.css v7.0.0  to 8.0.1 Issue##137

### PR DESCRIPTION
**Pull request by devr77**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

### CODE REVIEW

**Comment by devr77** [comment]
@wuda-io update this pr

**Comment by wuda-io** [comment]
Hey @devr77 
Thanks for your contribution!
Can you please rebase on v2-dev?

**Comment by wuda-io** [comment]
Also please use correct commit format.

**Comment by devr77** [comment]
I have formatted the commit message and after that I will rebase on v2-dev

**Comment by wuda-io** [comment]
LGTM! Happy easter everyone! 🐰

**Review by wuda-io — APPROVED** [review]

**Pull request merged**
