### PR TITLE
Added Example for alignment option

### LINKED ISSUE #275: dropdown alignment
How to change the dropdown modal alignment?

### PR DESCRIPTION
**Pull request by CypherpunkSamurai**
Added Example for dropdown alignment option

## Proposed changes
This PR adds documentation changes. New example for `alignment` option of dropdown component was added in dropdown documentation. This PR aims to fix #275 (More Examples for Dropdown alignment)

## Screenshots (if appropriate) or codepen:
- [ ] TODO

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md)**.
- [x] My commit messages follows the [conventional commit format](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md#submitting-your-pull-request)
- [x] My change requires a change to the documentation, and updated it accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by wuda-io** [comment]
Hey @CypherpunkSamurai 
Can you please edit your commit message to [conventional commit format](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md#submitting-your-pull-request)
Then I can merge it. Thank you.

**Comment by CypherpunkSamurai** [comment]
Sure. I got a little busy with college, please excuse the delay

**Comment by CypherpunkSamurai** [comment]
I keep forgetting the syntax for commit subject :P

I've fixed the commit now. please review :)

**Review by wuda-io — APPROVED** [review]
👍

**Pull request merged**
