### PR TITLE
Support Node.js 10 and above (Update node-sass and lint-staged)

### PR DESCRIPTION
**Pull request by nekonenene**
## Proposed changes

`npm install` succeeds with Node.js 8.x. But, its support has already ended.

This PR allows `npm install` with Node.js 10.x, 12.x, and 14.x.

### Why update node-sass?

Please see, https://www.npmjs.com/package/node-sass

> Supported Node.js versions vary by release

We are using node-sass v4.7.2, so the following error appears when `npm install` with Node.js 10 and above.

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Why update lint-staged?

lint-staged says "lint-staged requires at least version 6 of Node, please upgrade" and we cannot commit while using Node.js 10 and above. This is a bug and it fixed on v7.0.5. ( https://github.com/okonet/lint-staged/pull/434 )

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

I checked passing `npm install` with Node.js v10.22.1, v12.18.4, and v14.11.0.
(The error causing from `node-gyp` still appears, but it's ok. `node-gyp` is a dependency of `iltorb` and `iltorb` is an _optionalDependencies_ of `grunt-contrib-compress`.)

After that, I tried `npm run dev`, `npm run test`, `npx grunt release --oldver=1.0.0 --newver=1.0.1`, and these work well.

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Awesome =)
So the generated code still works?

Can you drop / remove the lockfile changes from this PR? Because npm will use the versions from your package.json and this should prevent merge conflicts when I update the lockfile on the target branch.

**Comment by nekonenene** [comment]
@DanielRuf 
> So the generated code still works?
Yes, as far as I can see, it seems generate same http://localhost:8000. 

> Can you drop / remove the lockfile changes from this PR?
I can, but I wonder when you will update lockfile. It's not a good idea to prevent updating package-lock.json because it will cause differences in the environment between developers.

**Comment by DanielRuf** [comment]
Lockfiles are not used by consumer (npm users) who install from npmjs.

The lockfile is just for CI.

After a PR is merged I update the lockfile. And it is mainly used by `npm ci`.

**Comment by nekonenene** [comment]
@DanielRuf OK!
```
npm ERR! Invalid: lock file's lint-staged@7.0.4 does not satisfy lint-staged@^7.0.5
npm ERR! Invalid: lock file's node-sass@4.7.2 does not satisfy node-sass@^4.14.1
```
https://travis-ci.com/github/materializecss/materialize/builds/185432205

Oh...what should i do now...

**Comment by DanielRuf** [comment]
Everything is ok. This is expected because we use `npm ci`.

**Pull request merged**
