### PR TITLE
Updated quickstart cdn

### PR DESCRIPTION
**Pull request by ChildishGiant**
## Proposed changes
Changed cdn in quickstart to use materializecss, not dogfalo. This means that if someone uses the cdn suggested in the quickstart, they get all the new stuff from this repo, not the old repo.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Smankusors** [comment]
hmm I just looked the CDN and it's not up to date with current repo... For example the license link in header is still the old one

https://cdn.jsdelivr.net/npm/@materializecss/materialize/dist/js/materialize.min.js

https://github.com/materializecss/materialize/blob/b75c47ba039dd8f0921fb1409783e37d792ed6fa/dist/js/materialize.min.js#L1-L5

I wonder how to update the CDN tho?

**Comment by ChildishGiant** [comment]
The cdn's pinned to the NPM release so will only get updated when that's pushed

**Review by DanielRuf — APPROVED** [review]

**Comment by DanielRuf** [comment]
> hmm I just looked the CDN and it's not up to date with current repo... For example the license link in header is still the old one
> 
> [cdn.jsdelivr.net/npm/@materializecss/materialize/dist/js/materialize.min.js](https://cdn.jsdelivr.net/npm/@materializecss/materialize/dist/js/materialize.min.js)

This is correct as I've just pushed the original 1.0.0 version with the original 1.0.0 tag and the code from it. Nothing to worry about for now.

**Review by Pierstoval — APPROVED** [review]

**Review by Smankusors — COMMENTED** [review]
on the other hand, if we want to update cdnjs, I think it's possible to create PR to update [this file](https://github.com/cdnjs/packages/blob/master/packages/m/materialize.json) on [cdnjs/packages](https://github.com/cdnjs/packages) repo?

**Comment by DanielRuf** [comment]
> on the other hand, if we want to update cdnjs, I think it's possible to create PR to update [this file](https://github.com/cdnjs/packages/blob/master/packages/m/materialize.json) on [cdnjs/packages](https://github.com/cdnjs/packages) repo?

No, because it is for the official package name `materialize`. A fork would need a separate version. In general we should use jsdelivr and unpkg.

**Comment by Smankusors** [comment]
> In general we should use jsdelivr and unpkg.

hmm pardon me but.... why is that? because it's easier than cdnjs? or something else? ❓

**Comment by DanielRuf** [comment]
> why is that? because it's easier than cdnjs? or something else? question

Easier, automatic, provides SRI hashes and much more.

https://www.jsdelivr.com/package/npm/jquery

grafik

And helpful statistics:

grafik

**Comment by DanielRuf** [comment]
And a few more features:

https://www.jsdelivr.com/package/npm/jquery?path=dist&tab=collection

grafik

**Review by Smankusors — APPROVED** [review]

**Comment by DanielRuf** [comment]
@ChildishGiant you should have received an invitation for the materializecss org and to the members team of it.

You can see and accept it at @materializecss

**Comment by ChildishGiant** [comment]
Thanks very much for the invite! I'm not overly well antiquated with the codebase but will help where I can 😄

**Pull request merged**
