### PR TITLE
docs : added a searchable link #225

### PR DESCRIPTION
**Pull request by MadhaviMandalia**
## Proposed changes

- Added a searchable link to the Icons description.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [ ] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by MadhaviMandalia** [comment]
Hi @DanielRuf ,
Why is lint comment massages failing, should I not mention (#225) issue in the commit massage please let me know.

Thanks.

**Comment by DanielRuf** [comment]
@MadhaviMandalia commitlint reports this:

> ⧗   input: Icon linked changed #225
> ✖   subject may not be empty [subject-empty]
> ✖   type may not be empty [type-empty]

It should look like this:

`fix: add link to searchable list` (type: present tense sentence)

We use the conventional config:
https://github.com/materializecss/materialize/blob/main/commitlint.config.js#L2

You can see some examples at https://www.conventionalcommits.org/en/v1.0.0/

**Review by DanielRuf — APPROVED** [review]

**Comment by DanielRuf** [comment]
@MadhaviMandalia all good with the commit :+1:

But you have to create a separate / new branch (please don't use the ?main` branch otherwise this could lead to conflicts), from the current version of our main branch.

I guess you need these commands:

```shell
git checkout -b main-temp # create copy of current branch
git branch -D main # delete old main branch
git remote add upstream git@github.com:materializecss/materialize.git # add upstream repo
git checkout main # checkout main of your fork
git merge upstream/main # update your main branch with the upstream one
git checkout -b fix/225-link-icon-list
git add ... & git commit -m '...'
git push -u origin fix/225-link-icon-list
# create new PR
```

Alternatively recreate your fork, create a new branch from the `main` branch, do the work there and push + create PR for this then.

**Review by roiLeo — COMMENTED** [review]
Why don't we use [this](https://fonts.google.com/icons) link instead?

**Comment by DanielRuf** [comment]
> Why don't we use [this](https://fonts.google.com/icons) link instead?

See https://github.com/materializecss/materialize/issues/225#issuecomment-998691875

**Comment by DanielRuf** [comment]
cc @ChildishGiant

**Pull request closed without merging**
