### PR TITLE
feat(autocomplete): add custom sort option

### LINKED ISSUE #115: Option for custom sort in autocomplete
Currently you can specify a custom "sortFunction" but this only controls which element wins in a 1v1 matchup, not how the matchups are made (Currently just uses array.sort). Adding this would allow end users to use libraries such as [fuse.js](https://fusejs.io/) to do more complex sorting and make results more accurate.

### PR DESCRIPTION
**Pull request by ChildishGiant**
Also renamed sortFunction to compareFunction (Closes #115)

## Proposed changes
Currently you can specify a custom "sortFunction" but this only controls which element wins in a 1v1 matchup, not how the matchups are made (Currently just uses array.sort). Adding this would allow end users to use libraries such as fuse.js to do more complex sorting and make results more accurate.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [x] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md)**.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ChildishGiant** [comment]
I've added docs for this: 
image
image

**Comment by ChildishGiant** [comment]
Rebased onto master

**Comment by DanielRuf** [comment]
It seems there is a commitlint violation.
Does someone want resolve this? That would be great =)

**Comment by ChildishGiant** [comment]
Not sure what's going on here, I'm gonna just close this and remake the commit.

**Pull request closed without merging**
