### PR TITLE
Copy text without creating textarea and use single container for copy success message

### PR DESCRIPTION
**Pull request by warrenrodrigues**
## Proposed changes

- Use a single message container to inform user when text is copied.
- Copy text without creating a textarea. Currently, the textarea appears at the bottom of the page. Screenshot below.

Getting Started - Materialize - materializecss github io

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/v1-dev/CONTRIBUTING.md)**.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Do you want to make a review? That would be awesome @christinavoudouris.

**Review by christinavoudouris — APPROVED** [review]
@warrenrodrigues this looks great! I'm glad someone was able to improve the code as I couldn't find a more eloquent solution. I tested it out in Codepen just now and agree that's optimal.

**Comment by warrenrodrigues** [comment]
@christinavoudouris Thank you. Good idea to offer an option to copy the code snippet.

**Comment by DanielRuf** [comment]
Thank you both for the great work!

**Pull request merged**
