### PR TITLE
Add default input styling to input type month

### PR DESCRIPTION
**Pull request by DyegoCosta**
## Proposed changes

Add `input[type=month]` to the list of text inputs to get default style.

## Screenshots (if appropriate) or codepen:

image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by wuda-io** [comment]
Hey @DyegoCosta!
Thank you for your contribution.
Can you please update the Commit-Message from "Add default input styling to input type month"
to "style(inputs): add default input styling to input type month"
You can validate your messages here online: https://commitlint.io/

**Comment by DyegoCosta** [comment]
@wuda-io hey! All set.

**Comment by Smankusors** [comment]
Thanks for pointing this out! 😄 

However, there's one missed case before we merge this. If we add a label, the label is not moved to the correct location, please refer the image below
image

I used the HTML below
```
<div class="input-field col s6">
  <input id="wawa" type="month">
  <label for="wawa">Last Name</label>
</div>
```

**Comment by wuda-io** [comment]
Now it looks good! Thanks for fixing the commit-message.
The issue @Smankusors pointed out needs to be fixed.
Where do we have to change the code too, to get the Label floating? I guess it is somewhere in the Javascript part.

Also we should consider fixing all Input-Types:
https://www.w3schools.com/html/html_form_input_types.asp

**Comment by Smankusors** [comment]
Sorry, the label is still not activated yet btw. Maybe because I'm using different branch? Please target your branch to `main` instead of `v2-dev`. I'm not sure that we will use this `v2-dev` branch in the future 😅 

Here's my recording where I tried it on the docs https://www.loom.com/share/a04640f67dd5488a9f2798aac4a7f011

**Review by Smankusors — APPROVED** [review]
oh goddamnit. It turns out the .js that I used was stuck on the old version. Oh welp there's a flaw on the grunt script 🤦 
I should fix this later...

LGTM

**Comment by Smankusors** [comment]
btw, I also invited you to join as the member of materializecss. Welcome 🎉

**Pull request merged**
