### PR TITLE
fix: for iOS13 selecting wrong Dropdownitem on Touchdevices fix #31

### LINKED ISSUE #31: dropdown.js still has the problem of misaligned taps
Dogfalo has fixed `select.js` to resolve the problem of the recognizing position of tap on iOS 13. Meanwhile, dropdown.js still has a such problem.

https://github.com/Dogfalo/materialize/commit/c0da34049deec36efbd4681f73b3446e92918ca8#commitcomment-36941624

I know this problem causes from the strange behavior of iOS 13 (and 14). https://developer.apple.com/forums/thread/120586

My current idea is to use`'ontouchend' in document.documentElement` to check if the browser supports _ontouchend_ and use this event if suppports. If not, then use the _onclick_ event. Though it will work well, I'm not sure if I can spend time solving this, so I wrote it down in this issue anyway.

### PR DESCRIPTION
**Pull request by wuda-io**
## Proposed changes
Fixes a long requested Bug for iOS Touch devices with a provided and tested Patch.
For details see: #31

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:
- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by wuda-io** [comment]
Finally! Haha. What a procedure. How can we ensure that contributers locally install commitlint?
Never used it.. i like it but if only ONE Commit-Message is incorrect and already pushed you
dont have any possibility to quick fix this!

This is not very contributor friendly.... maybe we should change this to enable easier contributing.
Greets

PS: Here is an Online-Tool if you want to be sure that your commit-Message is correct:
https://commitlint.io/

**Comment by DanielRuf** [comment]
> Finally! Haha. What a procedure. How can we ensure that contributers locally install commitlint?

Normally `husky` should install the hooks:
https://github.com/materializecss/materialize/blob/main/.husky/commit-msg

Did you run `npm i` locally?

**Comment by DanielRuf** [comment]
> i like it but if only ONE Commit-Message is incorrect and already pushed you
> dont have any possibility to quick fix this!

I use GitLense in VSCode and when you do a `git rebase -i HEAD~3` you can decide what to do with the last 3 commits (probably `reword`) and then start the rebase process and afterwards force-push to the same branch.

**Comment by ChildishGiant** [comment]
> How can we ensure that contributers locally install commitlint?

`npx cz` or `npm run commit` give a very easy interface for following conventional commit style, maybe adding more emphasis to that in the docs would help? https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md#submitting-your-pull-request (4.)

**Review by roiLeo — APPROVED** [review]

**Pull request merged**
