### PR TITLE
Upgrade testing framework, rewrite tests to use vanilla js instead of jQuery

### PR DESCRIPTION
**Pull request by tomwjerry**
## Proposed changes

This changes updates the testing framework to use grunt-contrib-jasmine 2.20 and jasmine 3.6 and removes to dependencies of jQuery from the testing framework. Thanks to @samschurter for the help with those fixes!
I converted all test code that use jQuery functions to vanilla js equivalent functions, that result in huge changes unfortunately. The vanilla js querySelector, querySelectorAll, getComputedStyle and getBoundingClientRect was used to replace the jQuery functions. In tests/spec/helper.js functions was added to replace Jasmine-jquery functions. I also changed many of the "var" to "let" to prevent variable scope creep, it is not a big issue but since one test already use "let" I decide to use "let" for all tests.

Also got some issues running test in random order.

Note: still uses jQuery because the dropdown bug. It is fixed by #57 When the dropdown bug is fixed, lines 11 - 13 in Gruntfile.js can be removed.

Relevant issue: #48

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Awesome =)

Please let us know if there is anything that you need help with or when this PR is ready for a first review.

Keep up the great work.

**Comment by tomwjerry** [comment]
I am done with it, I solved the toast error. I don't really understand why "CI / build (pull_request)" build succeed and "Travis CI - Pull Request" fails. Much could improved of course like the exists function that right now only check if the element is not null or undefined.

**Comment by Smankusors** [comment]
> I am done with it, I solved the toast error. I don't really understand why "CI / build (pull_request)" build succeed and "Travis CI - Pull Request" fails. Much could improved of course like the exists function that right now only check if the element is not null or undefined.

the error is about package.lock and package.json not in sync. This is normal when you changed the package.json, see #27 for the similiar issue. You don't need to fix this btw.

**Comment by DanielRuf** [comment]
Should we merge this @materializecss/members-write-access?

**Comment by DanielRuf** [comment]
> Note: still uses jQuery because the dropdown bug. It is fixed by #57 When the dropdown bug is fixed, lines 11 - 13 in Gruntfile.js can be removed.

#57 is merged now. So I guess we can remove the mentioned lines.

**Comment by Smankusors** [comment]
> Should we merge this @materializecss/members-write-access?

uh oh I currently have problem running tests on my Docker setup. Is the Chrome now required after `jasmine` upgrade? Currently I can't run it with an error "no usable sandbox". This seems can be fixed by giving a security option to my container or using `--no-sandbox` while launching Chrome. I think.... using `--no-sandbox` param should be a better solution for this? But I don't know where to put this param to... 😕 

Btw... I have a bad feeling the Travis will also fail because of this? 😰

**Comment by DanielRuf** [comment]
> using `--no-sandbox` param should be a better solution for this

This.

> Btw... I have a bad feeling the Travis will also fail because of this? 😰

Yep, it already failed. But we will move to GitHub Actions in the near future.

**Comment by DanielRuf** [comment]
> using `--no-sandbox` param should be a better solution for this

This.

> Btw... I have a bad feeling the Travis will also fail because of this? 😰

Yep, it already failed. But we will move to GitHub Actions in the near future.
But it failed there because of the lockfile. See https://travis-ci.com/github/materializecss/materialize/jobs/471491098

**Comment by tomwjerry** [comment]
I really don't know how to enable this `--no-sandbox` option :/ There is something called `sandboxArgs` that I tried now, the question is if it really works... I will try to figure out how docker works and see if I can find the right option.

**Comment by Smankusors** [comment]
> I really don't know how to enable this `--no-sandbox` option :/ There is something called `sandboxArgs` that I tried now, the question is if it really works... I will try to figure out how docker works and see if I can find the right option.

if you want to try the docker, you can use this command to create a new `node` container

```
docker run --name materializecss_build -it -u node node:8 bash
```

This will create a new container with NodeJS version 8 installed inside. Then you can also use `apt` like Ubuntu to install another program. The `-u node` parameter is used to run as "node" user inside the container.

**Review by Smankusors — APPROVED** [review]
It's LGTM now. Your last commit fixed that "no usable sandbox" issue.

---

Well except I got this message at random time (failed to load resource). I think this is not really important? The tests still run as expected though.
```
     ✓ should have an image that fills to full width of card
 Materialbox:
   Materialbox opens correctly with transformed ancestor
     - Opens a correctly placed overlay when clicked...
log: Failed to load resource: the server responded with a status of 403 (Forbidden)
     ✓ Opens a correctly placed overlay when clicked
 Fab
   FAB to toolbar
```

**Comment by DanielRuf** [comment]
> It's LGTM now. Your last commit fixed that "no usable sandbox" issue.
> 
> Well except I got this message at random time (failed to load resource). I think this is not really important? The tests still run as expected though.

Thanks, I also think we can merge this. If this is a flaky test then it was probably like this before. Maybe this will be resolved in another PR in the future.

**Pull request merged**
