### PR TITLE
chore: 🔖 release v1.1.0-alpha

### PR DESCRIPTION
**Pull request by ChildishGiant**
This would be the first release of 1.1.0. At this point it is still in development and is not recommended for use in production. This includes a changelog and builds. For a GitHub release, that can be made once merged. For a preview you can look on my branch: https://github.com/ChildishGiant/materialize/releases/tag/v1.1.0-alpha

### CODE REVIEW

**Comment by ChildishGiant** [comment]
@materializecss/members Anyone had the chance to look at this? I need to update it with the last few commits but other than that it should be all fine

**Review by nicknickel — APPROVED** [review]
LGTM

**Comment by Smankusors** [comment]
hmm wait, this v1.1.0-alpha doesn't include commits after 802bc19f9df2dca97c9941c6477c4ba9d11b3af3, is that correct?

**Comment by ChildishGiant** [comment]
Updated the pull with all the latest commits 😄

**Review by Smankusors — APPROVED** [review]
LGTM

@DanielRuf do we need anything else on this PR?

**Comment by ChildishGiant** [comment]
It's more about what needs to happen when this is merged, probably most important will be making the github release and running `npm publish` on the appropriate account.

**Comment by DanielRuf** [comment]
> It's more about what needs to happen when this is merged, probably most important will be making the github release and running `npm publish` on the appropriate account.

Exactly. Any volunteer who wants to do the release then?
Afaik I have already given some permissions on npmjs.

**Comment by ChildishGiant** [comment]
From a quick look it seems that @Smankusors and @nekonenene have permissions on the NPM package 👀

**Comment by Smankusors** [comment]
> From a quick look it seems that @Smankusors and @nekonenene have permissions on the NPM package 👀

hmm wait wait, I'm currently still busy at the moment...

btw is that as simple as login npm account and then execute `npm publish`?

**Comment by DanielRuf** [comment]
> btw is that as simple as login npm account and then execute `npm publish`?

Exactly. Bump version number locally (`1.1.0-alpha`), create a new build, test, create tag and commit, push both to the GitHub repo and then hit `npm publish`.

If something goes wrong we can unpublish versions with less than 100 installs or something like this and you can unpublish during a 24 hour period. We can test it with some `v1.0.0-rc.17` build so you can test the steps (or some other pseudo release candidate number just for testing that only we know, should be unpublished afterwards).

**Comment by DanielRuf** [comment]
> btw is that as simple as login npm account and then execute `npm publish`?

Exactly. Bump version number locally (`1.1.0-alpha`), create a new build, test, create tag and commit, push both to the GitHub repo and then hit `npm publish` (after `npm login` on the command line).

If something goes wrong we can unpublish versions with less than 100 installs or something like this and you can unpublish during a 24 hour period. We can test it with some `v1.0.0-rc.17` build so you can test the steps (or some other pseudo release candidate number just for testing that only we know, should be unpublished afterwards).

**Comment by ChildishGiant** [comment]
You should be able to pull this pr and publish from this, that way you have the changelog etc

**Comment by Smankusors** [comment]
Alright before I'm attempting to release, I want to ask about the versioning. Is this will be released as "1.1.0-alpha"? If in the future, the next version is still on alpha, should the next be : 
* 1.1.1-alpha
* 1.1.0-alpha.1; or
* something else?

If in the future still on alpha, should this version be named "1.1.0-alpha.1"?

**Comment by DanielRuf** [comment]
> 1.1.0-alpha.1; or

This. Then -rc, -rc.1 and final release milestone is v1.1.0.

**Comment by Smankusors** [comment]
Alright I think the process finished 🎉

- [x] npm run release
- [x] tagging a commit, push to GitHub
- [x] npm publish
- [x] release on GitHub

I think that's all...? Is there still something missing? 💭

**Comment by DanielRuf** [comment]
> I think that's all...? Is there still something missing? thought_balloon

Spread the word =)

Awesomne, looks good so far:

grafik

Great work :clap:

**Pull request merged**
