### PR TITLE
Fix #31 Bug on iOS 13 when selects wrong item on touch devices

### LINKED ISSUE #31: dropdown.js still has the problem of misaligned taps
Dogfalo has fixed `select.js` to resolve the problem of the recognizing position of tap on iOS 13. Meanwhile, dropdown.js still has a such problem.

https://github.com/Dogfalo/materialize/commit/c0da34049deec36efbd4681f73b3446e92918ca8#commitcomment-36941624

I know this problem causes from the strange behavior of iOS 13 (and 14). https://developer.apple.com/forums/thread/120586

My current idea is to use`'ontouchend' in document.documentElement` to check if the browser supports _ontouchend_ and use this event if suppports. If not, then use the _onclick_ event. Though it will work well, I'm not sure if I can spend time solving this, so I wrote it down in this issue anyway.

### PR DESCRIPTION
**Pull request by wuda-io**
## Proposed changes
Fixes a long requested Bug for iOS Touch devices with a provided and tested Patch.
For details see: https://github.com/materializecss/materialize/issues/31

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by Smankusors — CHANGES_REQUESTED** [review]
can you please fix the commit lint issue?

**Comment by wuda-io** [comment]
I dont know why this damn Linter does not accept my commit message.
I made 2 empty commits and it is still not accepted. How do I change the message accordingly?

**Comment by Smankusors** [comment]
> I dont know why this damn Linter does not accept my commit message. I made 2 empty commits and it is still not accepted. How do I change the message accordingly?

actually, you need to undo the commit, rename the message, and then force push to your branch. Not creating the new commits 😅

**Comment by wuda-io** [comment]
Yeah ok. Unfortunatly I dont know how to undo a commit 😅

**Comment by Smankusors** [comment]
how you do the git commit? CLI? VSCode? or other GUI program?

If you use CLI, you can use this command below to reset the state before last commit

```
git reset --soft HEAD~1
```

if you use VSCode, there's menu to do the undo commit

**Pull request closed without merging**
