### PR TITLE
Use the new issue form feature (a new type of issue template)

### PR DESCRIPTION
**Pull request by LoganTann**
## Proposed changes

Fixes https://github.com/materializecss/materialize/issues/296.

Replaces the current issue template by 2 forms (bug report, general issue)

image

## Screenshots (if appropriate) or codepen:

Live example : https://github.com/LoganTann/materialize/issues/new/choose

<details><summary>👇 Screenshots</summary>

Taken before the last commit that fixed some typos.

image

image

</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md)**.
- [x] My commit messages follows the [conventional commit format](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md#submitting-your-pull-request)
- [ ] My change requires a change to the documentation, and updated it accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by LoganTann** [comment]
Heya @materializecss/members-write-access is someone available to free some time to review my proposals ?

**Comment by DanielRuf** [comment]
Pinging @materializecss/members too. Anyone can do a PR review. So everyone feel free to give feedback.

Someone else or I can do the merge then.

**Comment by wuda-io** [comment]
Can you rename "general issue" to "improvement".
Because me as user doesnt know what is ment by general. I think we should seperate *bugs* and *improvements*

It is good to encourage users to provide code. This codepen is linked to your user. What happens when you close your account? I dont think this is neccessary, because often we only have screenshots or videos.

**Comment by LoganTann** [comment]
> Can you rename "general issue" to "improvement".

Agree

> This codepen is linked to your user. What happens when you close your account?

We do need to encourage users to provide code, and having a fresh codepen template will help this.

About the account, I agree this is not very good to have a personal account.

How about using this anonymous jsfiddle instead: https://jsfiddle.net/1es0zhaf/

In which we will update the template link at each update.

> I dont think this is neccessary, because often we only have screenshots or videos.

We may remove the "live example" input field, and ask instead to provide a link to a codepen, like the current issue template / improvement template

WDYT ?

**Comment by wuda-io** [comment]
I am not so familiar with codepen or jsfiddle. For a bug-issue the idea is very good. But i have to look at it in more detail how this works out in the long term. But we should give it a try and then improve over time.

The improvement-issue doesnt need the code-input. Here we could encourage the user to link references or upload concept images or screenshots. Also the *existing-bug* section could be removed here. If you adapt this things, I agree to merge.

**Comment by Smankusors** [comment]
I think we should mention "I have searched for duplicate or closed issues." in the first line so that the user don't waste time filling it out, and it turns out there's already existing one 🤔

**Comment by LoganTann** [comment]
Hello @wuda-io I applied your suggestions. Same for @Smankusors in which I renamed the "general issue" template into "improvement".

8ca2976c173ad032196a0b464c4fc32ee364fe82

**Review by Smankusors — APPROVED** [review]
Spongebob Many Thumbs

**Pull request merged**
