### PR TITLE
Spaces in Materialize CSS

### PR DESCRIPTION
**Pull request by rubenterre**
Add padding and margin with classes

## Proposed changes
Add padding and margin with classes. It's similar to Bulma CSS, this provides margin m* and padding p* helpers in all directions:

*t for top
*r for right
*b for bottom
*l for left
*x horizontally for both left and right
*y vertically for both top and bottom
You need to combine a margin/padding prefix with a direction suffix. For example:

for a margin-top, use mt-*
for a padding-bottom, use pb-*
for both margin-left and margin-right, use mx-*

```
<!-- Adds 1rem of margin at the bottom -->
<p class="mb-4">
  Margin bottom
</p>

<!-- Adds 0.25rem of padding on the left and the right -->
<p class="px-1">
  Horizontal padding
</p>

<!-- Removes the margin on the right and adds 0.75rem padding at the top -->
<p class="mr-0 pt-3">
  Both
</p>
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md)**.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ivanBell199** [comment]
If these styles are added, should `.no-padding` be deleted? It is used in the documentation in the[ Sidenav section](https://materializecss.github.io/materialize/sidenav.html). Also there are some other styles that as far as I can see are not mentioned in the docs:
```
.no-padding {
  padding: 0 !important;
}

.section.no-pad {
  padding: 0;
}

.section.no-pad-bot {
  padding-bottom: 0;
}

.section.no-pad-top {
  padding-top: 0;
}
```

**Comment by wuda-io** [comment]
Thank you for your contribution! Unfortunately the changes were made in the generated css files directly. The changes have to be made in the scss files i guess. Because if at the next change they are gone if the file is generated. Also the commit message have to be done correctly for the linter. You can use https://commitlint.io/ to check online.

**Comment by rubenterre** [comment]
> If these styles are added, should `.no-padding` be deleted? It is used in the documentation in the[ Sidenav section](https://materializecss.github.io/materialize/sidenav.html). Also there are some other styles that as far as I can see are not mentioned in the docs:
> ```
> .no-padding {
>   padding: 0 !important;
> }
> 
> .section.no-pad {
>   padding: 0;
> }
> 
> .section.no-pad-bot {
>   padding-bottom: 0;
> }
> 
> .section.no-pad-top {
>   padding-top: 0;
> }
> ```
> 

Thank you for your message! I'll change the syntax so it doesn't affect other classes.

**Comment by rubenterre** [comment]
> Thank you for your contribution! Unfortunately the changes were made in the generated css files directly. The changes have to be made in the scss files i guess. Because if at the next change they are gone if the file is generated. Also the commit message have to be done correctly for the linter. You can use https://commitlint.io/ to check online.

Ok, Thank you for the information! I will add the code to the scss file and commit again

**Comment by ivanBell199** [comment]
> 
> Thank you for your message! I'll change the syntax so it doesn't affect other classes.

I meant that your suggested styles can replace `.no-padding` as well as `.no-pad-bot` and so on, at least in a future version of the framework. We can use `.p-0` instead of `.no-padding`. So there is no need to keep the old css classes, especially in view of the fact that they are not directly mentioned in the docs.

**Comment by rubenterre** [comment]
> > Thank you for your message! I'll change the syntax so it doesn't affect other classes.
> 
> I meant that your suggested styles can replace `.no-padding` as well as `.no-pad-bot` and so on, at least in a future version of the framework. We can use `.p-0` instead of `.no-padding`. So there is no need to keep the old css classes, especially in view of the fact that they are not directly mentioned in the docs.

Yes, it is nothing new, but it seems to me that it could be an interesting feature to build more quickly.

**Comment by Smankusors** [comment]
This is nice feature, thanks 👍 

But first, please enlighten me, why we need this to be integrated to the materializecss? I mean for example, why don't we just use materializecss with tailwindcss.... Oh wait that's heavy.

Why don't we just use materializecss together with [basscss](https://basscss.com/)? Or other similiar utility libraries? Is the CSS conflicts?

**Comment by LoganTann** [comment]
> But first, please enlighten me

Yes, before submitting a feature PR, it's better to create an issue first to debate about how this feature should be implemented. It takes a little time in terms of discussion, but this way we can save a lot when coding that PR ;)

> why we need this to be integrated to the materializecss? I mean for example, why don't we just use materializecss with xxx ....

It might be cool to have this feature, so we don't have to rely on other libs.
When I worked on the docs, I wanted to add some padding/margins, but I had to use css.  
For small sections that requires only one or two rules, it's better to manipulate this using classes instead of a css rule.

But about the syntax, I prefer to remove the dash before the number : using `mb2` instead of `mb-2`, just as classes used in materialize grids.

**Comment by rubenterre** [comment]
> > But first, please enlighten me
> 
> Yes, before submitting a feature PR, it's better to create an issue first to debate about how this feature should be implemented. It takes a little time in terms of discussion, but this way we can save a lot when coding that PR ;)
> 
> > why we need this to be integrated to the materializecss? I mean for example, why don't we just use materializecss with xxx ....
> 
> It might be cool to have this feature, so we don't have to rely on other libs. When I worked on the docs, I wanted to add some padding/margins, but I had to use css. For small sections that requires only one or two rules, it's better to manipulate this using classes instead of a css rule.
> 
> But about the syntax, I prefer to remove the dash before the number : using `mb2` instead of `mb-2`, just as classes used in materialize grids.

I like the syntax you propose, so it is faster to write.

**Comment by DanielRuf** [comment]
I'm unsure because this leads to the case that materializecss creates its own utility class approach. In projects we normally create separate classes with longer names or just apply some tailwind classes if needed.

**Comment by LoganTann** [comment]
Closing for inactivity, feel free to reopen if needed.

**Pull request closed without merging**
