### PR TITLE
add support for smalltext on cards eg a small date at the top of a card

### PR DESCRIPTION
**Pull request by godalming123**
## Proposed changes
I have added a class `.card-smalltext` anything with this class in a `.card-content` in a `.card`will be capitiliased

## Screenshots (if appropriate) or codepen:
Screenshot from 2021-09-04 08-02-09

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/v1-dev/CONTRIBUTING.md)**.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. <- will do later
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Smankusors** [comment]
hmm I do wondering, why not writing them uppercase at the first place? Instead of using `text-transform`?

**Comment by godalming123** [comment]
well in [my use case](godalming123.github.io) the cards are lower case becuase of jekyll and I dont know how to make jekyll insert uppercase text so I used css instead

**Comment by godalming123** [comment]
it appears changing the branch that this is challanging added a load of comments that I did'nt do will create new pull request for this branch

**Comment by godalming123** [comment]
Update: I think I will work on other things this is fairly meaningless

**Pull request closed without merging**
