### PR TITLE
fix: floating labels do not work when type attribute is absent from input element #288

### PR DESCRIPTION
**Pull request by coffeeandwork**
## Proposed changes

Ensure that floating labels work correctly on input elements without an explicit `type` attribute.

## Screenshots (if appropriate) or codepen:
n/a

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Smankusors** [comment]
LGTM
btw @DyegoCosta, I asked you to review this since you recently edit this one. Do you think it's ok? Not breaking yours? 😅

**Review by DyegoCosta — CHANGES_REQUESTED** [review]
LGTM

You can also add a fixture in [tests/spec/forms/formsFixture.html](https://github.com/materializecss/materialize/blob/0e571463557854df9160d9510ebe8fd2ba900f19/tests/spec/forms/formsFixture.html) to cover this new field.

**Comment by coffeeandwork** [comment]
> LGTM
> 
> You can also add a fixture in [tests/spec/forms/formsFixture.html](https://github.com/materializecss/materialize/blob/0e571463557854df9160d9510ebe8fd2ba900f19/tests/spec/forms/formsFixture.html) to cover this new field.

Done.

**Review by DyegoCosta — APPROVED** [review]

**Review by Smankusors — APPROVED** [review]

**Comment by Smankusors** [comment]
Thanks for helping me review this one @DyegoCosta 😃 

Btw, I also invited you @coffeeandwork as the member of materializecss, welcome! 🎉

**Comment by coffeeandwork** [comment]
> Thanks for helping me review this one @DyegoCosta 😃
> 
> Btw, I also invited you @coffeeandwork as the member of materializecss, welcome! 🎉

Thank you all.

**Pull request merged**
