### PR TITLE
#6279: fixed aligning of dropdown with coverTrigger=false, when can align bottom

### PR DESCRIPTION
**Pull request by bugy**
This is another PR for Dogfalo#6279. The initial one is #4.

## Proposed changes
Original PR #4 fixes the alignment issue when there is not enough space **both** on the bottom and top sides.
This PR fixes the dropdown cover when there is not enough space at the bottom side, but still enough space at the top side (so scrolling is not needed).

## Screenshots (if appropriate) or codepen:
_(top and bottow browser panels are part of screenshot, to demonstrate which size is available)_
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:
- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Smankusors** [comment]
hmm wait I having difficulty to reproduce this bug btw. I tried with the updated doc website in https://materializecss.github.io/materialize/autocomplete.html, and it doesn't seems to cover the text field.

The screenshot you given, is that from materializecss.com or materializecss.github.io?

**Comment by bugy** [comment]
Hi @Smankusors I reproduced it locally. But it's the same on the doc website:
image

**Review by wuda-io — APPROVED** [review]
LGTM. Only an additional Condition. Tried to Reproduce the issue in the current version as displayed in the Screenshot and it also covers the Input-Field.

**Review by Smankusors — APPROVED** [review]
alright, for some reason, I can reproduce it now 😵

LGTM, thanks for the PR 👍

**Comment by DanielRuf** [comment]
Hi @bugy,

thanks for your contribution. You should have received an invitation for @materializecss a few moments ago.

**Comment by DanielRuf** [comment]
Hi @bugy,

thanks for your contribution. You should have received an invitation for @materializecss as part of the members group a few moments ago.

**Comment by bugy** [comment]
Hi @DanielRuf, thanks for the invitation :)

**Pull request merged**
