### PR TITLE
Make conventional commits more explicit

### PR DESCRIPTION
**Pull request by Smankusors**
## Proposed changes
I updated the PR template and the contributing doc, so that it's easier for the first time contributors and us reviewers when handling the conventional commits format. Let me know what do you guys think 😉 

(also merge two similiar checklist as one about change in docs)

## Screenshots (if appropriate) or codepen:
n/a

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md)**.
- [x] My commit messages follows the [conventional commit format](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md#submitting-your-pull-request)
- [ ] My change requires a change to the documentation, and updated it accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Comment by DyegoCosta** [comment]
What about add a git commit hook instead? https://github.com/conventional-changelog/commitlint/#add-hook
Seems reasonably fast on my machine.

Screen Shot 2022-10-18 at 1 52 47 PM

**Review by DyegoCosta — COMMENTED** [review]
What about add a git commit hook instead? https://github.com/conventional-changelog/commitlint/#add-hook
Seems reasonably fast on my machine.

Screen Shot 2022-10-18 at 1 52 47 PM

**Comment by DanielRuf** [comment]
@DyegoCosta that's what husky does, setting up Git hooks.

https://github.com/materializecss/materialize/blob/main/.husky/commit-msg

https://github.com/materializecss/materialize/blob/main/package.json#L60

I think we should upgrade husky to the latest available version. Afaik it also needs a `prepare` script in package.json.

**Comment by DyegoCosta** [comment]
OH I did not notice we had that already in the project, I think my local was behind the upstream. Wouldn't be better to fix it instead of adding this new checkbox then? I added it to my outdated branch (with [this command](https://github.com/conventional-changelog/commitlint/#add-hook)) and it worked as expected (screenshot above).

**Comment by wuda-io** [comment]
I think it only works on Unix machines, I will test it.
But since it is checked locally, it can bypassed anyhow, so an additional checkbox is not bad as reminder.

**Review by LoganTann — APPROVED** [review]
Proposals approved

**Comment by Smankusors** [comment]
@DyegoCosta sadly the commit hook doesn't work when the contributor edited directly from github.com or github.dev 😞

**Comment by DanielRuf** [comment]
@Smankusors that is as expected since the browser-based IDE has no real shell environment.

That should not be a problem for us. As we plan to onboard more members with write access, there will be more volunteers who can fix commit messages in PRs if needed.

**Review by DyegoCosta — APPROVED** [review]

**Pull request merged**
