### PR TITLE
Update and rearrange content for readability

### PR DESCRIPTION
**Pull request by ajoygp**
Break up the first para, make minor changes, and place the contents under relevant sub-topics.  Add definition to floating action buttons based on https://material.io/archive/guidelines/components/buttons.html#.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md)**.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by LoganTann — COMMENTED** [review]
Code is good.

**Comment by LoganTann** [comment]
However, the pipeline fails due to your commit message. You need to change it.

do `git commit --amend -m "doc(button-content): Update and rearrange content for readability
"`

then `git push -f`

**Comment by LoganTann** [comment]
Also, more personal question, did you make this contribution for the hacktoberfest?

**Comment by ajoygp** [comment]
> 

Actually no.  I found the repo when looking for a CSS framework. Thought I could contribute to docs and jumped right in. Didn't realize it would show in hacktoberfest until you mentioned it. (Btw i am still  a newbie, going through the odin project at the moment.

**Comment by Smankusors** [comment]
oh uh, it should be lower case after colon, and the type should be `docs`

so the commit message should be `docs(button-content): update and rearrange content for readability`

**Comment by ajoygp** [comment]
> oh uh, it should be lower case after colon, and the type should be `docs`
> 
> so the commit message should be `docs(button-content): update and rearrange content for readability`
> 
> you can validate it with https://commitlint.io btw

Changed.

**Comment by DanielRuf** [comment]
> @materializecss/maintainers I don't have the right to run the CI. Can someone take care of it in order to get this validated for merge ?

I did now.

**Comment by LoganTann** [comment]
@DanielRuf I don't have the rights to merge, may you review this and merge it once it's approved ?

**Comment by DanielRuf** [comment]
@LoganTann now you should be able to merge. If not, please let me know.

Bildschirmfoto 2022-10-04 um 22 59 12
Bildschirmfoto 2022-10-04 um 22 59 56

**Comment by LoganTann** [comment]
all good @DanielRuf, thanks you !

**Comment by DanielRuf** [comment]
hi @ajoygp,

thanks for your contribution, which is very welcome.

We have invited you now as member of the materialize org. Happy to have you on board.

image

**Pull request merged**
