### PR TITLE
#5949 enabled prettier for all the formats

### PR DESCRIPTION
**Pull request by bugy**
## Proposed changes
Enabled prettier for all formats, to avoid argues about codestyle. Now all the styles are defined by prettier (and some can be configured if needed) and code is formatted on commit

## Screenshots (if appropriate) or codepen:
Should not affect any behaviour

## Types of changes
Only formatting 

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:
- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by bugy** [comment]
@materializecss/members as discussed in my other PR, there was a problem with leading zero (.4 vs 0.4). We agreed with @roiLeo and @DanielRuf to apply it via eslint.

After digging deeper, I found that this should be done by prettier (by default), but it wasn't enabled for scss files. So I made a brave move and enabled it for all the formats 😅 
What do you think about it?

**Comment by wuda-io** [comment]
LGTM.
Many changes here. Only looked through some of the code, pretty awesome that it formats Code-Styling automatically on Commit. I guess everybody has their own style preferences while coding so this is a nice step forward to standardization. Good work 👍

**Comment by ChildishGiant** [comment]
Do you know what style is used for JS? I proposed using standard in #79

**Comment by DanielRuf** [comment]
> Do you know what style is used for JS? I proposed using standard in #79

Afaik prettier is an opiniated formatter that applies its own rules (one reason why I do not really like prettier and prefer other linters and formatters like eslint).

To use the eslint config you have to add some more packages and configure prettier:
https://www.robinwieruch.de/prettier-eslint

https://prettier.io/docs/en/integrating-with-linters.html

https://github.com/prettier/prettier-eslint

For standardjs see https://standardjs.com/awesome.html#automatic-code-formatters and https://www.npmjs.com/package/prettier-standard

https://github.com/prettier/prettier/issues/2364
https://prettier.io/docs/en/comparison.html

From https://prettier.io/docs/en/:
> Prettier enforces a consistent code style (i.e. code formatting that won’t affect the AST) across your entire codebase because it disregards the original styling* by parsing it away and re-printing the parsed AST with its own rules that take the maximum line length into account, wrapping code when necessary.

**Comment by bugy** [comment]
To be honest, I'm fine with any :) I checked the result changes from prettier and they look good to me. 
I could also use prettier-eslint instead
For CSS we would need to add another linter, though.

**Comment by bugy** [comment]
Just FYI I just compared `standard` vs `prettier-standard` on materializecss project and the former introduces much more changes after formatting.

**Comment by roiLeo** [comment]
Is #79 related ?

**Comment by bugy** [comment]
Yes, partially. 
This PR is about enabling prettier for non-js files (at the moment it works only for JS).
#79 is about replacing prettier with **JS** standard style

So, even though these 2 PRs are about different types of files, but they contradict in usage of prettier. So we should decide, if we go with dedicated formatters per language (standard JS, styling, etc.) or use prettier for everything

**Comment by DanielRuf** [comment]
What is the current status? I see many conflicts due to other changes.

**Comment by bugy** [comment]
Hi @DanielRuf sorry for the late response
To be honest, as far as I remember, there were several PRs and suggestions regarding styling. And I don't know what was selected (I don't follow discussions in other PRs).

This PR mainly enables default prettier for scss, HTML and js. 

If we agree on smth, I would create a separate PR (to avoid solving merge conflicts). Basically, my main changes in the PR are only regarding styling configs. And 100+ files are changed, because I applied these styles before commit (as per hook)

**Comment by wuda-io** [comment]
Hey. Thank you for the contribution! I think there would be too much changes here, so I close it.

**Comment by DanielRuf** [comment]
> There is a way to run it for changed files (but not lines). Unfortunately, I don't know how to run it only for new files.

We can safely do that with lint-staged and husky.

**Pull request closed without merging**
