### PR TITLE
feat: Add options to `M.AutoInit()`

### PR DESCRIPTION
**Pull request by linkdd**
## Proposed changes

The `M.AutoInit()` function did not allow to pass options to the individual components. This PR introduces an `options` parameter (optional) allowing the user to configure each component:

```typescript
M.AutoInit(document.body, {
  Dropdown: {
    constrainWidth: false,
  },
  FloatingActionButtonOptions: {
    toolbarEnabled: true,
  },
})
```

## Screenshots (if appropriate) or codepen:

N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md)**.
- [x] My commit messages follows the [conventional commit format](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md#submitting-your-pull-request)
- [x] My change requires a change to the documentation, and updated it accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by wuda-io — APPROVED** [review]
LGTM

**Comment by wuda-io** [comment]
Can you also update the documentation please and make a PR with a short description and the new options.
That would be awesome and we can merge it.
Check out the repo here https://github.com/materializecss/materialize-docs

**Comment by linkdd** [comment]
@wuda-io Not sure if you saw the other PR as requested, but it is done. I hope it's what you wanted. Feel free to ask request any change if needed.

**Comment by wuda-io** [comment]
Ok nice 👍 I merged the docs part in the dev branch. see https://github.com/materializecss/materialize-docs/pull/16
I also send you an invitation to join the materialize team.

**Pull request merged**
