### PR TITLE
Remove extra indentation and trailing spaces

### PR DESCRIPTION
**Pull request by notSagyo**
## Proposed changes

- Remove extra indentation and trailing spaces which serve no purpose from _waves.scss.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by wuda-io** [comment]
Please update your commit-message to 
`refactor(waves): Remove extra indentation and trailing spaces`
Also check out: https://commitlint.io/

**Comment by notSagyo** [comment]
> Please update your commit-message to `refactor(waves): Remove extra indentation and trailing spaces` Also check out: https://commitlint.io/

Commit message updated. Thank you for the heads up.

**Review by wuda-io — APPROVED** [review]
LGTM. I hope we see also some code improvements from you in future,
not only space cleaning 😜

**Comment by DanielRuf** [comment]
Hi @notSagyo,

thanks for your contribution to materialize.
You should have received an invitation to @materializecss and the member group.

grafik

**Comment by notSagyo** [comment]
> Hi @notSagyo,
> 
> thanks for your contribution to materialize. You should have received an invitation to @materializecss and the member group.
> 
> grafik

Thank you @DanielRuf,
I'll consider it, as I'm still getting used to the public GitHub environment and workflow !

**Pull request merged**
