### PR TITLE
fix/accessibility/enhancement(featureDiscovery) initialization, accessibility and spec test

### PR DESCRIPTION
**Pull request by gselderslaghs**
## Proposed changes
**Feature Discovery TapTarget trigger is not working as described in #523**
This was caused by a bug where the initial triggering element was not handled within the event handler
In this fix I also addressed deleting the clone of the triggering element that initially handles closing the Feature Discover component by increasing the z-order on the initial trigger element and by a ternary operator to wether open/close the Feature Discovery when click event on this element is triggered

**Multiple instances not programmatically being initialized #252**
This also applies to #523 where a manual event handler needed to be defined in order to make the tap-targets work with the defined triggering element

**Accessibility #541**
- Implemented keyboard interaction
- Implemented aria-expanded
- Implemented tab-index, this also works with child elements inside the tap target container

**Implemented specification tests**
Specification tests have been implemented based on initializing, opening and closing the Feature Discovery component

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue).
- [X] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:
- [X] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md)**.
- [X] My commit messages follows the [conventional commit format](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md#submitting-your-pull-request)
- [ ] My change requires a change to the documentation, and updated it accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by gselderslaghs** [comment]
This pull-request is still work in progress, as I've found that when using buttons inside the component as it's currently not possible to tab from the open/close triggering element directly to the elements inside the Tap Target container

**Comment by gselderslaghs** [comment]
> This pull-request is still work in progress, as I've found that when using buttons or other tabbable content inside the component it's currently not possible to tab from the open/close triggering element directly to the elements inside the Tap Target container

This was more of a local issue where the triggering element was placed in an additional wrapper instead of near the tap-target element itself

**Comment by gselderslaghs** [comment]
Update:

**Multiple instances not programmatically being initialized**
This resolves that a manual event handler needed to be defined in order to make the tap-targets work with the defined triggering element

**Accessibility**
- Implemented keyboard interaction
- Implemented aria-expanded
- Implemented tab-index, this also works with child elements inside the tap target container

**Implemented specification tests**
Specification tests have been implemented based on initializing, opening and closing the Feature Discovery component

This pull request is ready for review

**Review by wuda-io — APPROVED** [review]
LGTM

**Pull request merged**
