### PR TITLE
Improving CONTRIBUTING document

### PR DESCRIPTION
**Pull request by Smankusors**
## Proposed changes
In this PR I proposed to update the CONTRIBUTING.md doc. Here's the list I updated:
* improving ToC
* updating labels section
* mention convention commit format in PR guide
* removed translations section (we don't have any other languages in the docs)

I'm not sure about labels section. We haven't formally (?) arrange the labels that we created and used? Like which labels used on PR only, or issue only? Or what guideline for the `good first issue` label?

Please let me know if there's something wrong/missing. Edits are also welcome to improve this document and/or PR. 😉

Thanks,

### CODE REVIEW

**Comment by ivanBell199** [comment]
Are there any translators working on this project? Any tranlsations planned? If there are no doubts that the framework will grow and be maintained, I would like to contribute as an English-Russian and English-Ukrainian translator

**Review by roiLeo — APPROVED** [review]

**Comment by Smankusors** [comment]
> Are there any translators working on this project? Any translations planned? If there are no doubts that the framework will grow and be maintained, I would like to contribute as an English-Russian and English-Ukrainian translator

hmm from the original maintainers I don't see any translation actions beside of putting an email in the contributing doc. As of myself, I don't have that plan. IMO I think Google Translate is already enough. 😄 

Btw @DanielRuf, What do you think?

**Comment by DanielRuf** [comment]
> Btw @DanielRuf, What do you think?

If we would have requests for translations (keeping them synced is extra work) and have a small team for this, then it could be a benefit for users.

But so far I see not many reasons to manage translations ourself.

**Comment by Smankusors** [comment]
Hmm so how do we proceed with translation section in CONTRIBUTING doc? How do we implement translation across the docs?

**Comment by DanielRuf** [comment]
Personally I find it complicated to keep translations in sync, especially on websites where every PR which changes or adds new texts requires extra work from some translation team.

There are services like phrase, poedit and more which allow people to translate the texts, manage them and keep everything in sync.

Otherwise it will become cumbersome like in phpMussel where we had to check and update every translated docs after sonething has changed in the original version or they would differ too much after some time: 
https://github.com/phpMussel/Docs/commits/master

I would say: let's replace the section with a text that we are looking for translators, an efficient solution so translators are independent of Git, GitHub and PRs and keep the files so far for reference.

**Comment by Smankusors** [comment]
Hmm alright, let's discuss the translation on https://github.com/materializecss/materialize/discussions/182

Btw... how about the labels?

**Comment by DanielRuf** [comment]
> [](https://github.com/materializecss/materialize/discussions/182)
> 
> Btw... how about the labels?

The labels are fine. Let's move on with this here. I will merge this now =)

**Pull request merged**
